# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile on, match:title ^(Microsoft-edge)$
windowrule = tile on, match:title ^(Brave-browser)$
windowrule = tile on, match:title ^(Chromium)$

windowrule = float on, match:title ^(pavucontrol)$
windowrule = float on, match:class ^(waypaper)$
windowrule = float on, match:class ^(io.missioncenter.MissionCenter)$
windowrule = float on, match:title ^(blueman-manager)$
windowrule = float on, match:title ^(nm-connection-editor)$
windowrule = float on, match:title ^(qalculate-gtk)$
windowrule = float on, match:class ^(org.gnome.Calculator)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(it.mijorus.smile)$
windowrule = float on, match:title ^(fdm)$
windowrule = float on, match:title ^(Thunar)$
windowrule = float on, match:title ^(xarchiver)$
windowrule = float on, match:class ^(id.glicole.nadekodon)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule= float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule= float on, match:class ^(dropTerm)$


# Browser Picture in Picture
windowrule {
    name = PiP
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = on
    keep_aspect_ratio = on
    move = monitor_w*0.73 monitor_h*0.72
    size = monitor_w*0.25 monitor_h*0.25
    pin = on
    content = video
    opacity = 1.0 override
}

# idleinhibit
windowrule = idle_inhibit fullscreen,match:fullscreen 1 # Available modes: none, always, focus, fullscreen

# Thunar
windowrule {
    name = Thunar-Progress
    match:initial_title = ^(File Operation Progress)$
    float = on
    size = monitor_w*0.6 monitor_h*0.1
    center = on
}

windowrule {
    name = Thunar-Rename
    match:initial_title = ^(Rename)(.*)$
    float = on
    size = monitor_w*0.6 monitor_h*0.1
    center = on
}

# Image Viewers
windowrule = float on, match:class ^(org.photoqt.PhotoQt)$
windowrule = size 50%, match:class ^(org.photoqt.PhotoQt)$
windowrule = float on, match:class ^(imv)$
windowrule = size 50%, match:class ^(imv)$
windowrule = float on, match:class ^(org.gnome.Loupe)$
windowrule = float on, match:class ^(org.kde.gwenview)$
windowrule = size 50%, match:class ^(org.kde.gwenview)$

# Screenshot
windowrule = float on, match:class ^(swappy)$
windowrule = pin on, match:class ^(swappy)$

# Temporary since hyprland no longer accept size from the floating app
# windowrule = max_size monitor_w*0.8 monitor_h*0.8, match:float 1
