color0       #3B3A3C
color8       #999A9A
color1       #8D4D47
color9       #BB665F
color2       #606238
color10      #80824A
color3       #A46D66
color11      #DA9188
color4       #658D95
color12      #87BCC7
color5       #6E969A
color13      #93C8CD
color6       #969797
color14      #C8CAC9
color7       #DBDCDC
color15      #DBDCDC