color0       #00000F
color8       #A09596
color1       #47704E
color9       #5F9668
color2       #437F95
color10      #59A9C6
color3       #528094
color11      #6DAAC5
color4       #94776A
color12      #C59F8D
color5       #A08D88
color13      #D5BCB5
color6       #A38D8E
color14      #DABCBE
color7       #E4D5D6
color15      #E4D5D6