[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "e"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the parent pane"

[[mgr.prepend_keymap]]
on   = [ "<C-m>" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
