[font]
size = 8.5
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

[window]
opacity = 0.8
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true
